sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qJ/WZTggawF+mPb703T4KwwjvHAVMb7aSjAnBj6MYUpOi7oLpHEnlOLJB7uuroT1WTSfMGyLw48mdrhrmCO0nHbi7q86U9/nFEArJ7wRfn9358b4a3G/gDKJpug2o7hqFyzCOemqxdyAm1FwBo8/lNtLOuGZMjsF2jortWftwoaTUOJ6PaVeeZUeUdm+R16g4+pv0NrZJPv5h1diQBszbWnlWBf119TRd+9a3rAJ9u5VBVHUw4xxnn42oG4SYjKlKShOmAa8D5RxEGRPHXjl4S9Ht9LEsl8hnLqK2olUEKx5/FS+1fse3VunFcUiVSyxWOuyvSrlWQD5iZxHa0ezPd9rdIW+TLHs3PfPqNK0Q2YoRipyV+foRgqlnZdPQmavqRp0xDBDMjVW+p3c6jglestrnPfniMBaeIXZM4qOIEYNjEDeEOjUn65pu7z8TUSkyPf18wzIWf7N12c3k7FGpBdgnEvg1aTM2CKlEUGJd79hfsxC6drZK7F6wOIZ/v06ljOEmZlcqf+Aw/gDLfEqjH3EPp4b0p1H/Us+fuFJ7/ybWXUC0qhO67PISIJEgJsogLCy/lqPvzc/vVUAwpoh8sSeM1jkdv5Xq8ScUcJ2PWGVLjn4Pg717Z9WeVBF6a/kcsqp+qcrHW6eft0aFZ1jukX4OZ+e+7c/WviRb2s81Ss=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Survivors-of-the-Chancellor--Diary-of-J.R.-Kazallon-Passenger_1652
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy